### ISSUE TITLE
No permite eliminar comentario

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#113]
## Proceso

1. Iniciar sesión
2. Realizar un comentario

## Resultado esperado

Cuando un usuario realiza un comentario, se espera poder editar o eliminar dicho comentario. 

## Resultado actual

No permite editar ni eliminar el comentario

## Captura

<img width="490" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/9b6beda5-26a8-46ee-bbf5-e4fede12be1e">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by FranDelgado20** [comment]
#127 
Se agregó la función para editar y eliminar el comentario realizado por un usuario.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/127/commits/ff30796
