### ISSUE TITLE
No permite editar la fecha del turno 

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#114]
## Proceso

1. Iniciar sesión
2. Solicitar un turno
3. Ir al carrito
4. Seleccionar editar turno

## Resultado esperado

Se espera poder cambiar la fecha del turno en caso de ser necesario

## Resultado actual

No permite editar la fecha del turno

## Captura

<img width="322" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/180f67f6-a91e-4718-84aa-e68af34fb908">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#126 
Se añade en la función y formulario de editar turnos las variables de "fecha" y "hora", permitiendo que el usuario pueda modificar las mismas.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/126/commits/13ba463ac79dabc8932f01a70cebe16ca221a86e
