### ISSUE TITLE
Logo del footer no redirige al inicio 

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#115]
## Proceso

1. Entrar a la pagina
2. Dirigirse al footer
3. El logo no redirige al inicio

## Resultado esperado

Los iconos, imagenes de logo deberian redirigir al inico

## Resultado actual

No redirige al inicio

## Captura

<img width="324" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/b22a2085-f1af-4211-8400-9164ddec7f7c">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#122 
Se agregó un Link de react-router-dom como etiqueta padre del img del footer para que al clickear el logo de la página nos redirija a inicio.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/122/commits/a0fb9481965201f7b5def064726ffae19d3d0d3f
