### ISSUE TITLE
Campo "Consulta"

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#116]
## Proceso

1. Iniciar sesión
2. Consultar sobre un plan

## Resultado esperado

El campo consulta o descripción, por lo general es opcional. Esto dado que para el usuario, podria no ser necesario adjuntar una información adicional.

## Resultado actual

El campo consulta es obligatorio.

## Captura

<img width="353" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/dd602bdc-ecc6-495d-b3b5-f96932e14fca">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#122 
Se elimina la validación de consulta en Formik y el esquema de validación de Yup, de esta manera este campo ya no es obligatorio cuando se solicita el plan.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/122/commits/a0fb9481965201f7b5def064726ffae19d3d0d3f
