### ISSUE TITLE
Turno para una fecha antigua

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#117]
## Proceso

1. Iniciar sesión
2. Diligenciar los campos
3. Seleccionar una fecha antigua
4. Solicitar un turno

## Resultado esperado

A la hora de solicitar un turno, debe ser para una fecha futura. 

## Resultado actual

Permite solicitar un turno para una fecha anterior a la actual

## Captura

<img width="466" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/57e02218-ca39-4e75-ab88-0cdc74cd2e75">

<img width="523" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/73f86417-e37f-4bb3-ab25-9ce292b83edd">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#128 
Se añade una validación mediante la librería Yup donde prohibe al usuario solicitar un turno con fecha anterior a la actual.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/128/commits/4c66855e881663204f485f2177687d03d6931535
