### ISSUE TITLE
Tamaño de la celda "cantidad"

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#118]
## Proceso

1. Iniciar sesión
2. Agregar un producto al carrito
3. Ir al carrito

## Resultado actual

La celda de la cantidad no contiene el 100% del alto.

## Captura
<img width="455" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/ef76ab3e-584f-4f48-a785-66324503f9e8">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#122 
Se añade un media query en la fila de la tabla para que aumente el height, quedando igual en toda la fila.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/122/commits/a0fb9481965201f7b5def064726ffae19d3d0d3f
