### ISSUE TITLE
Accesibilidad en imagenes

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#119]
## Proceso

1. Iniciar sesión como administrador
2. Editar un producto
3. Borrar partes de la url de la imagen

## Resultado esperado

Se espera que los elementos que sean `<img />`, posean el atributo `alt`. Recordemos que por temas de accesibilidad y buenas prácticas se recomienda colocar los atributos alt en todas las imagenes.

## Resultado actual

Actualmente no posee texto alternativo

## Captura

<img width="409" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/80648f0d-a8b7-4e0e-ac90-51fc2f17f89f">

<img width="606" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/b7fbdc71-df86-4988-a9cd-93956f7f1f43">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#123 
Se modifica el alt del elemento <img> que era "Imagen" y pasa a ser el nombre de cada producto.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/123/commits/c17a936d83eca3ea997a3b194fe70634bddb8d2b
