### ISSUE TITLE
No debería permitir eliminar el usuario admin

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#120]
## Proceso

1. Iniciar sesión como administrador
2. Eliminar usuarios

## Resultado esperado

El usuario admin, no deberia permiti eliminarse a si mismo

## Resultado actual

Permite la selección de eliminar

## Captura

<img width="778" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/243791a3-4703-4264-a2f9-3a33d463ccd9">

<img width="830" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/f804e67c-0ab4-441a-840c-3f2845d6e42f">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#124 
Se agrega una validación a la función de eliminar usuarios, diciendo que si el rol del mismo es "admin" no sea posible eliminarlo.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/124/commits/6a9d9a87fd329b87a64aba66a5dec1e7d82a9de1
