### ISSUE TITLE
Falla al editar como administrador

### ISSUE THREAD

**Issue by castromaciel** [FranDelgado20/TuksonPets#121]
## Proceso

1. Iniciar sesión como administrador
2. Editar el numero de telefono por uno ya existente

## Resultado esperado

Se espera que no permita la edicion, pero a su vez debe informar al usuario si hubo algún error (en este caso especificar el error)

## Resultado actual

Falla al editar, pero no informa el error al usuario

## Captura

<img width="785" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/3a7e19ff-fb7e-4fcb-8100-716fbea99ca2">

<img width="417" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/37a2b173-4fad-4bbd-95d5-4f4e004713a8">

<img width="1264" alt="image" src="https://github.com/FranDelgado20/TuksonPets/assets/83432755/44f6c606-6643-49fd-9371-f6eb52d70eb9">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by SantiJaime** [comment]
#124 
Se modifica la función y formulario de editar usuario, impidiendo que se pueda editar el número de teléfono del mismo.
Commit: https://github.com/FranDelgado20/TuksonPets/pull/124/commits/89a744a9b545dbeccea00214a33f79933d46c150
